#![allow(unused_imports, unused_variables)]
extern crate testbed2;
extern crate tb_enum;
extern crate tb_same1;
extern crate tb_same2;
extern crate tb_simple;
extern crate testbed1;
extern crate tb_names;
use testbed2::api::many_param_interface::ManyParamInterfaceTrait as testbed2_ManyParamInterfaceTrait;
use testbed2::implementation::many_param_interface::ManyParamInterface as testbed2_ManyParamInterface;
use testbed2::core_types::many_param_interface_shared::new_shared_many_param_interface as new_shared_testbed2_many_param_interface;
use testbed2::api::nested_struct1_interface::NestedStruct1InterfaceTrait as testbed2_NestedStruct1InterfaceTrait;
use testbed2::implementation::nested_struct1_interface::NestedStruct1Interface as testbed2_NestedStruct1Interface;
use testbed2::core_types::nested_struct1_interface_shared::new_shared_nested_struct1_interface as new_shared_testbed2_nested_struct1_interface;
use testbed2::api::nested_struct2_interface::NestedStruct2InterfaceTrait as testbed2_NestedStruct2InterfaceTrait;
use testbed2::implementation::nested_struct2_interface::NestedStruct2Interface as testbed2_NestedStruct2Interface;
use testbed2::core_types::nested_struct2_interface_shared::new_shared_nested_struct2_interface as new_shared_testbed2_nested_struct2_interface;
use testbed2::api::nested_struct3_interface::NestedStruct3InterfaceTrait as testbed2_NestedStruct3InterfaceTrait;
use testbed2::implementation::nested_struct3_interface::NestedStruct3Interface as testbed2_NestedStruct3Interface;
use testbed2::core_types::nested_struct3_interface_shared::new_shared_nested_struct3_interface as new_shared_testbed2_nested_struct3_interface;
use tb_enum::api::enum_interface::EnumInterfaceTrait as tb_enum_EnumInterfaceTrait;
use tb_enum::implementation::enum_interface::EnumInterface as tb_enum_EnumInterface;
use tb_enum::core_types::enum_interface_shared::new_shared_enum_interface as new_shared_tb_enum_enum_interface;
use tb_same1::api::same_struct1_interface::SameStruct1InterfaceTrait as tb_same1_SameStruct1InterfaceTrait;
use tb_same1::implementation::same_struct1_interface::SameStruct1Interface as tb_same1_SameStruct1Interface;
use tb_same1::core_types::same_struct1_interface_shared::new_shared_same_struct1_interface as new_shared_tb_same1_same_struct1_interface;
use tb_same1::api::same_struct2_interface::SameStruct2InterfaceTrait as tb_same1_SameStruct2InterfaceTrait;
use tb_same1::implementation::same_struct2_interface::SameStruct2Interface as tb_same1_SameStruct2Interface;
use tb_same1::core_types::same_struct2_interface_shared::new_shared_same_struct2_interface as new_shared_tb_same1_same_struct2_interface;
use tb_same1::api::same_enum1_interface::SameEnum1InterfaceTrait as tb_same1_SameEnum1InterfaceTrait;
use tb_same1::implementation::same_enum1_interface::SameEnum1Interface as tb_same1_SameEnum1Interface;
use tb_same1::core_types::same_enum1_interface_shared::new_shared_same_enum1_interface as new_shared_tb_same1_same_enum1_interface;
use tb_same1::api::same_enum2_interface::SameEnum2InterfaceTrait as tb_same1_SameEnum2InterfaceTrait;
use tb_same1::implementation::same_enum2_interface::SameEnum2Interface as tb_same1_SameEnum2Interface;
use tb_same1::core_types::same_enum2_interface_shared::new_shared_same_enum2_interface as new_shared_tb_same1_same_enum2_interface;
use tb_same2::api::same_struct1_interface::SameStruct1InterfaceTrait as tb_same2_SameStruct1InterfaceTrait;
use tb_same2::implementation::same_struct1_interface::SameStruct1Interface as tb_same2_SameStruct1Interface;
use tb_same2::core_types::same_struct1_interface_shared::new_shared_same_struct1_interface as new_shared_tb_same2_same_struct1_interface;
use tb_same2::api::same_struct2_interface::SameStruct2InterfaceTrait as tb_same2_SameStruct2InterfaceTrait;
use tb_same2::implementation::same_struct2_interface::SameStruct2Interface as tb_same2_SameStruct2Interface;
use tb_same2::core_types::same_struct2_interface_shared::new_shared_same_struct2_interface as new_shared_tb_same2_same_struct2_interface;
use tb_same2::api::same_enum1_interface::SameEnum1InterfaceTrait as tb_same2_SameEnum1InterfaceTrait;
use tb_same2::implementation::same_enum1_interface::SameEnum1Interface as tb_same2_SameEnum1Interface;
use tb_same2::core_types::same_enum1_interface_shared::new_shared_same_enum1_interface as new_shared_tb_same2_same_enum1_interface;
use tb_same2::api::same_enum2_interface::SameEnum2InterfaceTrait as tb_same2_SameEnum2InterfaceTrait;
use tb_same2::implementation::same_enum2_interface::SameEnum2Interface as tb_same2_SameEnum2Interface;
use tb_same2::core_types::same_enum2_interface_shared::new_shared_same_enum2_interface as new_shared_tb_same2_same_enum2_interface;
use tb_simple::api::void_interface::VoidInterfaceTrait as tb_simple_VoidInterfaceTrait;
use tb_simple::implementation::void_interface::VoidInterface as tb_simple_VoidInterface;
use tb_simple::core_types::void_interface_shared::new_shared_void_interface as new_shared_tb_simple_void_interface;
use tb_simple::api::simple_interface::SimpleInterfaceTrait as tb_simple_SimpleInterfaceTrait;
use tb_simple::implementation::simple_interface::SimpleInterface as tb_simple_SimpleInterface;
use tb_simple::core_types::simple_interface_shared::new_shared_simple_interface as new_shared_tb_simple_simple_interface;
use tb_simple::api::simple_array_interface::SimpleArrayInterfaceTrait as tb_simple_SimpleArrayInterfaceTrait;
use tb_simple::implementation::simple_array_interface::SimpleArrayInterface as tb_simple_SimpleArrayInterface;
use tb_simple::core_types::simple_array_interface_shared::new_shared_simple_array_interface as new_shared_tb_simple_simple_array_interface;
use tb_simple::api::no_properties_interface::NoPropertiesInterfaceTrait as tb_simple_NoPropertiesInterfaceTrait;
use tb_simple::implementation::no_properties_interface::NoPropertiesInterface as tb_simple_NoPropertiesInterface;
use tb_simple::core_types::no_properties_interface_shared::new_shared_no_properties_interface as new_shared_tb_simple_no_properties_interface;
use tb_simple::api::no_operations_interface::NoOperationsInterfaceTrait as tb_simple_NoOperationsInterfaceTrait;
use tb_simple::implementation::no_operations_interface::NoOperationsInterface as tb_simple_NoOperationsInterface;
use tb_simple::core_types::no_operations_interface_shared::new_shared_no_operations_interface as new_shared_tb_simple_no_operations_interface;
use tb_simple::api::no_signals_interface::NoSignalsInterfaceTrait as tb_simple_NoSignalsInterfaceTrait;
use tb_simple::implementation::no_signals_interface::NoSignalsInterface as tb_simple_NoSignalsInterface;
use tb_simple::core_types::no_signals_interface_shared::new_shared_no_signals_interface as new_shared_tb_simple_no_signals_interface;
use tb_simple::api::empty_interface::EmptyInterfaceTrait as tb_simple_EmptyInterfaceTrait;
use tb_simple::implementation::empty_interface::EmptyInterface as tb_simple_EmptyInterface;
use tb_simple::core_types::empty_interface_shared::new_shared_empty_interface as new_shared_tb_simple_empty_interface;
use testbed1::api::struct_interface::StructInterfaceTrait as testbed1_StructInterfaceTrait;
use testbed1::implementation::struct_interface::StructInterface as testbed1_StructInterface;
use testbed1::core_types::struct_interface_shared::new_shared_struct_interface as new_shared_testbed1_struct_interface;
use testbed1::api::struct_array_interface::StructArrayInterfaceTrait as testbed1_StructArrayInterfaceTrait;
use testbed1::implementation::struct_array_interface::StructArrayInterface as testbed1_StructArrayInterface;
use testbed1::core_types::struct_array_interface_shared::new_shared_struct_array_interface as new_shared_testbed1_struct_array_interface;
use testbed1::api::struct_array2_interface::StructArray2InterfaceTrait as testbed1_StructArray2InterfaceTrait;
use testbed1::implementation::struct_array2_interface::StructArray2Interface as testbed1_StructArray2Interface;
use testbed1::core_types::struct_array2_interface_shared::new_shared_struct_array2_interface as new_shared_testbed1_struct_array2_interface;
use tb_names::api::nam_es::NamEsTrait as tb_names_NamEsTrait;
use tb_names::implementation::nam_es::NamEs as tb_names_NamEs;
use tb_names::core_types::nam_es_shared::new_shared_nam_es as new_shared_tb_names_nam_es;

fn main() {
    println!("ApiGear Rust SDK Examples");
    println!("========================");

    // Create default implementations
    let _testbed2_many_param_interface = testbed2_ManyParamInterface::default();
    let _testbed2_nested_struct1_interface = testbed2_NestedStruct1Interface::default();
    let _testbed2_nested_struct2_interface = testbed2_NestedStruct2Interface::default();
    let _testbed2_nested_struct3_interface = testbed2_NestedStruct3Interface::default();
    let _tb_enum_enum_interface = tb_enum_EnumInterface::default();
    let _tb_same1_same_struct1_interface = tb_same1_SameStruct1Interface::default();
    let _tb_same1_same_struct2_interface = tb_same1_SameStruct2Interface::default();
    let _tb_same1_same_enum1_interface = tb_same1_SameEnum1Interface::default();
    let _tb_same1_same_enum2_interface = tb_same1_SameEnum2Interface::default();
    let _tb_same2_same_struct1_interface = tb_same2_SameStruct1Interface::default();
    let _tb_same2_same_struct2_interface = tb_same2_SameStruct2Interface::default();
    let _tb_same2_same_enum1_interface = tb_same2_SameEnum1Interface::default();
    let _tb_same2_same_enum2_interface = tb_same2_SameEnum2Interface::default();
    let _tb_simple_void_interface = tb_simple_VoidInterface::default();
    let _tb_simple_simple_interface = tb_simple_SimpleInterface::default();
    let _tb_simple_simple_array_interface = tb_simple_SimpleArrayInterface::default();
    let _tb_simple_no_properties_interface = tb_simple_NoPropertiesInterface::default();
    let _tb_simple_no_operations_interface = tb_simple_NoOperationsInterface::default();
    let _tb_simple_no_signals_interface = tb_simple_NoSignalsInterface::default();
    let _tb_simple_empty_interface = tb_simple_EmptyInterface::default();
    let _testbed1_struct_interface = testbed1_StructInterface::default();
    let _testbed1_struct_array_interface = testbed1_StructArrayInterface::default();
    let _testbed1_struct_array2_interface = testbed1_StructArray2Interface::default();
    let _tb_names_nam_es = tb_names_NamEs::default();

    // Create shared (Arc<dyn Trait>) implementations
    let _shared_testbed2_many_param_interface = new_shared_testbed2_many_param_interface();
    let _shared_testbed2_nested_struct1_interface = new_shared_testbed2_nested_struct1_interface();
    let _shared_testbed2_nested_struct2_interface = new_shared_testbed2_nested_struct2_interface();
    let _shared_testbed2_nested_struct3_interface = new_shared_testbed2_nested_struct3_interface();
    let _shared_tb_enum_enum_interface = new_shared_tb_enum_enum_interface();
    let _shared_tb_same1_same_struct1_interface = new_shared_tb_same1_same_struct1_interface();
    let _shared_tb_same1_same_struct2_interface = new_shared_tb_same1_same_struct2_interface();
    let _shared_tb_same1_same_enum1_interface = new_shared_tb_same1_same_enum1_interface();
    let _shared_tb_same1_same_enum2_interface = new_shared_tb_same1_same_enum2_interface();
    let _shared_tb_same2_same_struct1_interface = new_shared_tb_same2_same_struct1_interface();
    let _shared_tb_same2_same_struct2_interface = new_shared_tb_same2_same_struct2_interface();
    let _shared_tb_same2_same_enum1_interface = new_shared_tb_same2_same_enum1_interface();
    let _shared_tb_same2_same_enum2_interface = new_shared_tb_same2_same_enum2_interface();
    let _shared_tb_simple_void_interface = new_shared_tb_simple_void_interface();
    let _shared_tb_simple_simple_interface = new_shared_tb_simple_simple_interface();
    let _shared_tb_simple_simple_array_interface = new_shared_tb_simple_simple_array_interface();
    let _shared_tb_simple_no_properties_interface = new_shared_tb_simple_no_properties_interface();
    let _shared_tb_simple_no_operations_interface = new_shared_tb_simple_no_operations_interface();
    let _shared_tb_simple_no_signals_interface = new_shared_tb_simple_no_signals_interface();
    let _shared_tb_simple_empty_interface = new_shared_tb_simple_empty_interface();
    let _shared_testbed1_struct_interface = new_shared_testbed1_struct_interface();
    let _shared_testbed1_struct_array_interface = new_shared_testbed1_struct_array_interface();
    let _shared_testbed1_struct_array2_interface = new_shared_testbed1_struct_array2_interface();
    let _shared_tb_names_nam_es = new_shared_tb_names_nam_es();

    println!("All interfaces instantiated successfully.");
}
