pub mod same_struct1_interface_data;
pub mod same_struct1_interface_shared;
pub mod same_struct2_interface_data;
pub mod same_struct2_interface_shared;
pub mod same_enum1_interface_data;
pub mod same_enum1_interface_shared;
pub mod same_enum2_interface_data;
pub mod same_enum2_interface_shared;
pub mod test_helpers;
